/**
 *
 *  RestfulOrderItemsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulOrderItemsCtrl.h"
#include <string>


void RestfulOrderItemsCtrl::getOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   OrderItems::PrimaryKeyType &&id)
{
    RestfulOrderItemsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulOrderItemsCtrl::updateOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      OrderItems::PrimaryKeyType &&id)
{
    RestfulOrderItemsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulOrderItemsCtrl::deleteOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      OrderItems::PrimaryKeyType &&id)
{
    RestfulOrderItemsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulOrderItemsCtrl::get(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulOrderItemsCtrlBase::get(req, std::move(callback));
}

void RestfulOrderItemsCtrl::create(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulOrderItemsCtrlBase::create(req, std::move(callback));
}
