/**
 *
 *  RestfulOrdersCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulOrdersCtrlBase.h"

#include "Orders.h"
using namespace drogon;
using namespace drogon_model::cafeteria_db;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the orders table.
 */

class RestfulOrdersCtrl: public drogon::HttpController<RestfulOrdersCtrl>, public RestfulOrdersCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulOrdersCtrl::getOne,"/orders/{1}",Get,Options);
    ADD_METHOD_TO(RestfulOrdersCtrl::updateOne,"/orders/{1}",Put,Options);
    ADD_METHOD_TO(RestfulOrdersCtrl::deleteOne,"/orders/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulOrdersCtrl::get,"/orders",Get,Options);
    ADD_METHOD_TO(RestfulOrdersCtrl::create,"/orders",Post,Options);
    //ADD_METHOD_TO(RestfulOrdersCtrl::update,"/orders",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Orders::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Orders::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Orders::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
