/**
 *
 *  RestfulOrdersCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulOrdersCtrl.h"
#include <string>


void RestfulOrdersCtrl::getOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               Orders::PrimaryKeyType &&id)
{
    RestfulOrdersCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulOrdersCtrl::updateOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Orders::PrimaryKeyType &&id)
{
    RestfulOrdersCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulOrdersCtrl::deleteOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Orders::PrimaryKeyType &&id)
{
    RestfulOrdersCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulOrdersCtrl::get(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulOrdersCtrlBase::get(req, std::move(callback));
}

void RestfulOrdersCtrl::create(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulOrdersCtrlBase::create(req, std::move(callback));
}
