/**
 *
 *  RestfulMenusCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulMenusCtrl.h"
#include <string>


void RestfulMenusCtrl::getOne(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback,
                              Menus::PrimaryKeyType &&id)
{
    RestfulMenusCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulMenusCtrl::updateOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Menus::PrimaryKeyType &&id)
{
    RestfulMenusCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulMenusCtrl::deleteOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Menus::PrimaryKeyType &&id)
{
    RestfulMenusCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulMenusCtrl::get(const HttpRequestPtr &req,
                           std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulMenusCtrlBase::get(req, std::move(callback));
}

void RestfulMenusCtrl::create(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulMenusCtrlBase::create(req, std::move(callback));
}
