/**
 *
 *  RestfulMenusCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulMenusCtrlBase.h"

#include "Menus.h"
using namespace drogon;
using namespace drogon_model::cafeteria_db;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the menus table.
 */

class RestfulMenusCtrl: public drogon::HttpController<RestfulMenusCtrl>, public RestfulMenusCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulMenusCtrl::getOne,"/menus/{1}",Get,Options);
    ADD_METHOD_TO(RestfulMenusCtrl::updateOne,"/menus/{1}",Put,Options);
    ADD_METHOD_TO(RestfulMenusCtrl::deleteOne,"/menus/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulMenusCtrl::get,"/menus",Get,Options);
    ADD_METHOD_TO(RestfulMenusCtrl::create,"/menus",Post,Options);
    //ADD_METHOD_TO(RestfulMenusCtrl::update,"/menus",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Menus::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Menus::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Menus::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
