/**
 *
 *  RestfulOrderItemsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulOrderItemsCtrlBase.h"

#include "OrderItems.h"
using namespace drogon;
using namespace drogon_model::cafeteria_db;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the order_items table.
 */

class RestfulOrderItemsCtrl: public drogon::HttpController<RestfulOrderItemsCtrl>, public RestfulOrderItemsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulOrderItemsCtrl::getOne,"/orderitems/{1}",Get,Options);
    ADD_METHOD_TO(RestfulOrderItemsCtrl::updateOne,"/orderitems/{1}",Put,Options);
    ADD_METHOD_TO(RestfulOrderItemsCtrl::deleteOne,"/orderitems/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulOrderItemsCtrl::get,"/orderitems",Get,Options);
    ADD_METHOD_TO(RestfulOrderItemsCtrl::create,"/orderitems",Post,Options);
    //ADD_METHOD_TO(RestfulOrderItemsCtrl::update,"/orderitems",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                OrderItems::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   OrderItems::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   OrderItems::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
